name: Sync Fork (main and development)

on:
  schedule:
    - cron: '0 0 * * *'  # Execute every day at 00:00
  workflow_dispatch:

jobs:
  update-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Add upstream
        run: git remote add upstream https://github.com/4Practica/devCorner.git
      - name: Fetch upstream
        run: git fetch upstream
      - name: Merge upstream/main
        run: git merge upstream/main --allow-unrelated-histories
      - name: Push to origin
        run: git push
        env:
          GIT_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

  update-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development
      - name: Add upstream
        run: git remote add upstream https://github.com/4Practica/devCorner.git
      - name: Fetch upstream
        run: git fetch upstream
      - name: Merge upstream/development
        run: git merge upstream/development --allow-unrelated-histories
      - name: Push to origin
        run: git push
        env:
          GIT_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
