name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar a las 00:00 AM todos los días

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add upstream
        run: git remote add upstream https://github.com/4Practica/devCorner.git
      - name: Fetch upstream
        run: git fetch upstream
      - name: Merge upstream/development
        run: git merge upstream/development
      - name: Push to origin
        run: git push
