name: Sync Fork

on:
  push:
    branches: [development, main]
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Add remote
        run: git remote add fork https://github.com/Jdvd01/devCorner-deploy.git
      - name: Push to fork
        run: git push -u fork ${{ github.ref }}
        env:
          GIT_TOKEN: ${{ secrets.WORKFLOW_TOKEN_JDVD }}
